export const LIST_COURSE_SUCCESS = "LIST_COURSE_SUCCESS";
export const LIST_COURSE_FAILED = "LIST_COURSE_FAILED";
export const LIST_COURSE_LESSON_SUCCESS = "LIST_COURSE_LESSON_SUCCESS";
export const LIST_COURSE_LESSON_FAILED = "LIST_COURSE_LESSON_FAILED";
